<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Event_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get event by eventid
     */
    function get_event($eventid)
    {
			  $search = $this->load->database('search', TRUE);
        return $search->get_where('events',array('eventid'=>$eventid))->row_array();
    }
        
    /*
     * Get all events
     */
    function get_all_events()
    {
			  $search = $this->load->database('search', TRUE);
        $search->order_by('eventid', 'desc');
        return $search->get('events')->result_array();
    }
        
    /*
     * function to add new event
     */
    function add_event($params)
    {
				$search = $this->load->database('search', TRUE);
        $search->insert('events',$params);
        return $search->insert_id();
    }
    
    /*
     * function to update event
     */
    function update_event($eventid,$params)
    {
				$search = $this->load->database('search', TRUE);
        $search->where('eventid',$eventid);
        return $search->update('events',$params);
    }
    
    /*
     * function to delete event
     */
    function delete_event($eventid)
    {
				$search = $this->load->database('search', TRUE);
        return $search->delete('events',array('eventid'=>$eventid));
    }
}
